sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
  - cargo install --force cargo-audit
script:
  - RUSTFLAGS=-Dwarnings cargo build
  - cargo clippy --all-targets -- -D warnings
  - cargo fmt --all -- --check
  - cargo audit
