sudo: false
dist: trusty
language: rust
rust:
  - nightly

branches:
  only:
    - master

before_script:
  - rustup component add rustfmt clippy-preview
  - cargo install --force cargo-audit
script:
  - RUSTFLAGS=-Dwarnings cargo build
  - cargo clippy --all-targets -- -D warnings
  - cargo fmt --all -- --check
  - cargo audit
