[package]
name = "ct-tools"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = ">=0.3.0-alpha", features = ["compat"] }
tokio = ">=0.2.0-alpha.2"
tokio-io = ">=0.2.0-alpha"
tokio-net = ">=0.2.0-alpha"
tokio-process = ">=0.3.0-alpha"
tokio-rustls = ">=0.12.0-alpha"
tokio-service = "*"
net2 = "*"

acme-client = { version = "*", default-features = false }

base64 = ">=0.10"

byteorder = "*"

chrono = "*"

dirs = "*"

structopt = "*"
structopt-derive = "*"

hex = "*"

hyper = { version = "0.13.0-a.0", git = "https://github.com/hyperium/hyper" }
hyper-rustls = { version = "0.18.0-alpha", git = "https://github.com/markuskobler/hyper-rustls", branch = "futures-0.3" }
tower-service = "0.3.0-alpha"

openssl = ">=0.10"

ring = "*"

rustls = { version = ">=0.11", features = ["dangerous_configuration"] }

serde = "*"
serde_derive = "*"
serde_json = "*"

pem = "*"

prettytable-rs = "*"

tera = ">=0.10.4"

url = "*"

webpki = ">=0.18.0"
