[package]
name = "ct-tools"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]

[dependencies]
acme-client = "*"

base64 = "*"

byteorder = "*"

chrono = "*"

clap = "*"

hex = "*"

hyper = ">= 0.11"
hyper-rustls = ">=0.6"

openssl = "*"

rayon = "*"

ring = "*"

rustls = { version = ">=0.8", features = ["dangerous_configuration"] }

serde = "*"
serde_derive = "*"
serde_json = "*"

pem = "*"

prettytable-rs = "*"

tera = ">=0.10.4"

url = "*"
