[package]
name = "ct-tools"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]

[dependencies]
futures = "*"
futures-await = { git = "https://github.com/alexcrichton/futures-await" }
tokio-core = "*"
tokio-io = "*"
tokio-process = "*"
tokio-rustls = "*"
tokio-service = "*"
net2 = "*"

acme-client = "*"

base64 = "*"

byteorder = "*"

chrono = "*"

clap = "*"

hex = "*"

hyper = ">=0.11"
hyper-rustls = ">=0.11"

openssl = "*"

ring = ">=0.12"

rustls = { version = ">=0.11", features = ["dangerous_configuration"] }

serde = "*"
serde_derive = "*"
serde_json = "*"

pem = "*"

prettytable-rs = "*"

tera = ">=0.10.4"

url = "*"
