[package]
name = "ct-tools"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]

[dependencies]
base64 = "*"

byteorder = "*"

clap = "*"

hex = "*"

hyper = "*"
hyper-rustls = ">=0.5"

rayon = "*"

ring = "*"

rustls = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"

pem = "*"

prettytable-rs = "*"

tempfile = "*"

tera = ">=0.10.4"

url = "*"
